class NotificationType:
    ACCOUNT_APPROVED = "ACCOUNT_APPROVED"
    ACCOUNT_REJECTED = "ACCOUNT_REJECTED"
    ACCOUNT_ACTIVATION = "ACCOUNT_ACTIVATION"
    PASSWORD_RESET = "PASSWORD_RESET"
    CONTRIBUTION_RECEIVED = "CONTRIBUTION_RECEIVED"
    CONTRIBUTION_REMINDER = "CONTRIBUTION_REMINDER"
    CONTRIBUTION_PROPOSAL = "CONTRIBUTION_PROPOSAL"
    INVESTMENT_CREATED = "INVESTMENT_CREATED"
    INVESTMENT_UPDATE = "INVESTMENT_UPDATE"
    GROUP_ANNOUNCEMENT = "GROUP_ANNOUNCEMENT"
    MEMBERSHIP_ADDED = "MEMBERSHIP_ADDED"
    PENALTY_ISSUED = "PENALTY_ISSUED"
    SECURITY_ALERT = "SECURITY_ALERT"
    GENERAL = "GENERAL"

    CHOICES = (
        (ACCOUNT_APPROVED, "Account Approved"),
        (ACCOUNT_REJECTED, "Account Rejected"),
        (ACCOUNT_ACTIVATION, "Account Activation"),
        (PASSWORD_RESET, "Password Reset"),
        (CONTRIBUTION_RECEIVED, "Contribution Received"),
        (CONTRIBUTION_REMINDER, "Contribution Reminder"),
        (CONTRIBUTION_PROPOSAL, "Contribution Proposal"),
        (INVESTMENT_CREATED, "Investment Created"),
        (INVESTMENT_UPDATE, "Investment Update"),
        (GROUP_ANNOUNCEMENT, "Group Announcement"),
        (MEMBERSHIP_ADDED, "Membership Added"),
        (PENALTY_ISSUED, "Penalty Issued"),
        (SECURITY_ALERT, "Security Alert"),
        (GENERAL, "General"),
    )
