class NotificationType:
    ACCOUNT_APPROVED = "ACCOUNT_APPROVED"
    ACCOUNT_REJECTED = "ACCOUNT_REJECTED"
    ACCOUNT_ACTIVATION = "ACCOUNT_ACTIVATION"
    PASSWORD_RESET = "PASSWORD_RESET"
    CONTRIBUTION_RECEIVED = "CONTRIBUTION_RECEIVED"
    CONTRIBUTION_APPROVED = "CONTRIBUTION_APPROVED"
    CONTRIBUTION_REMINDER = "CONTRIBUTION_REMINDER"
    CONTRIBUTION_PROPOSAL = "CONTRIBUTION_PROPOSAL"
    LOAN_APPROVED = "LOAN_APPROVED"
    LOAN_REJECTED = "LOAN_REJECTED"
    LOAN_DISBURSED = "LOAN_DISBURSED"
    LOAN_REPAYMENT_RECEIVED = "LOAN_REPAYMENT_RECEIVED"
    LOAN_REPAYMENT_VERIFIED = "LOAN_REPAYMENT_VERIFIED"
    LOAN_OVERDUE = "LOAN_OVERDUE"
    INVESTMENT_CREATED = "INVESTMENT_CREATED"
    INVESTMENT_UPDATE = "INVESTMENT_UPDATE"
    GROUP_ANNOUNCEMENT = "GROUP_ANNOUNCEMENT"
    MEMBERSHIP_ADDED = "MEMBERSHIP_ADDED"
    PENALTY_ISSUED = "PENALTY_ISSUED"
    SECURITY_ALERT = "SECURITY_ALERT"
    GENERAL = "GENERAL"

    CHOICES = (
        (ACCOUNT_APPROVED, "Account Approved"),
        (ACCOUNT_REJECTED, "Account Rejected"),
        (ACCOUNT_ACTIVATION, "Account Activation"),
        (PASSWORD_RESET, "Password Reset"),
        (CONTRIBUTION_RECEIVED, "Contribution Received"),
        (CONTRIBUTION_APPROVED, "Contribution Approved"),
        (CONTRIBUTION_REMINDER, "Contribution Reminder"),
        (CONTRIBUTION_PROPOSAL, "Contribution Proposal"),
        (LOAN_APPROVED, "Loan Approved"),
        (LOAN_REJECTED, "Loan Rejected"),
        (LOAN_DISBURSED, "Loan Disbursed"),
        (LOAN_REPAYMENT_RECEIVED, "Loan Repayment Received"),
        (LOAN_REPAYMENT_VERIFIED, "Loan Repayment Verified"),
        (LOAN_OVERDUE, "Loan Overdue"),
        (INVESTMENT_CREATED, "Investment Created"),
        (INVESTMENT_UPDATE, "Investment Update"),
        (GROUP_ANNOUNCEMENT, "Group Announcement"),
        (MEMBERSHIP_ADDED, "Membership Added"),
        (PENALTY_ISSUED, "Penalty Issued"),
        (SECURITY_ALERT, "Security Alert"),
        (GENERAL, "General"),
    )
