# Generated by Django 5.2.10 on 2026-02-12 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_contribution_penalty_autosavingconfig_and_more'),
        ('payments', '0003_mpesatransaction_mpesa_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='finance.contribution'),
        ),
    ]
