# Generated by Django 5.2.10 on 2026-03-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_is_penalty_enabled_group_min_saving_amount_and_more'),
        ('payments', '0004_mpesatransaction_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='groups.group'),
        ),
    ]
