# Generated by Django 5.2.10 on 2026-02-04 06:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['due_date']},
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='paid_on',
            new_name='paid_date',
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='penalty_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('LATE', 'Late'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='penalty',
            name='applied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contribution',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_contributions', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='finance.contribution'),
        ),
    ]
