# Generated by Django 5.2.10 on 2026-02-06 11:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_contribution_options_and_more'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='System suggested or manually adjusted penalty', max_digits=10),
        ),
        migrations.CreateModel(
            name='AutoSavingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly auto-save amount (minimum 500)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Day of month to generate (1-28)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_saving_configs', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_saving_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySavingGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_for_month', models.DateField(help_text='The month this contribution was generated for')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='finance.autosavingconfig')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_generation', to='finance.contribution')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_targets', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='autosavingconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'group'), name='unique_active_config_per_user_group'),
        ),
        migrations.AddConstraint(
            model_name='monthlysavinggeneration',
            constraint=models.UniqueConstraint(fields=('config', 'generated_for_month'), name='unique_monthly_generation'),
        ),
    ]
