# Generated by Django 5.2.10 on 2026-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('LATE', 'Late'), ('OVERDUE', 'Overdue'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
