# Generated by Django 5.2.10 on 2026-02-24 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_contribution_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user being penalized', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='contribution',
            field=models.ForeignKey(blank=True, help_text='Optional link to a specific contribution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='finance.contribution'),
        ),
    ]
