# Generated by Django 5.2.10 on 2026-02-25 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_penalty_user_alter_penalty_contribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="is_manual_entry",
            field=models.BooleanField(
                default=False,
                help_text="True when the contribution was reported manually for admin verification.",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="reported_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contribution",
            name="reported_paid_date",
            field=models.DateField(
                blank=True,
                help_text="Date the member reports they paid outside the system.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="reported_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M_PESA", "M-Pesa"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("BANK_DEPOSIT", "Bank Deposit"),
                    ("CASH", "Cash"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="reported_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="contribution",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_finance_contributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
