# Generated by Django 5.2.10 on 2026-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_contribution_manual_proposal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosavingconfig',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penalty',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
