# Generated by Django 5.2.10 on 2026-03-02 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_autosavingconfig_is_archived_penalty_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='investments/attachments/'),
        ),
        migrations.AddField(
            model_name='investment',
            name='business_case',
            field=models.TextField(blank=True, help_text='Optional business case summary'),
        ),
        migrations.AddField(
            model_name='investment',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Investment Duration in months', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='lock_in_period',
            field=models.PositiveIntegerField(blank=True, help_text='Lock-in Period in months', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='min_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum Required Capital', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='payout_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('AT_MATURITY', 'At Maturity')], default='AT_MATURITY', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='return_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable'), ('COMPOUND', 'Compound'), ('PROFIT_BASED', 'Profit-based')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, help_text='Proposed Principal Amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateField(blank=True, help_text='Proposed Maturity Date', null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateField(help_text='Proposed Start Date'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.CreateModel(
            name='InvestmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_status_actions', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='finance.investment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
