# Generated by Django 5.2.10 on 2026-03-02 21:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_investment_attachment_investment_business_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='finance.investment')),
            ],
            options={
                'ordering': ['-payout_date'],
            },
        ),
    ]
