# Generated by Django 5.2.10 on 2026-03-03 00:00

from datetime import date
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q
from django.utils import timezone


def _month_start(value):
    return value.replace(day=1)


def seed_cycles_and_monthly_records(apps, schema_editor):
    FinancialCycle = apps.get_model("finance", "FinancialCycle")
    Contribution = apps.get_model("finance", "Contribution")
    Investment = apps.get_model("finance", "Investment")
    MonthlyContributionRecord = apps.get_model("finance", "MonthlyContributionRecord")
    Group = apps.get_model("groups", "Group")

    now = timezone.now()
    groups = Group.objects.all()
    cycle_map = {}

    for group in groups:
        years = set(
            Contribution.objects.filter(group_id=group.id).values_list("due_date__year", flat=True)
        )
        years.update(
            Investment.objects.filter(group_id=group.id).values_list("start_date__year", flat=True)
        )

        years = {int(y) for y in years if y}
        if not years:
            continue

        latest_year = max(years)
        for year in sorted(years):
            cycle_name = f"{year} Cycle"
            defaults = {
                "start_date": date(year, 1, 1),
                "end_date": date(year, 12, 31),
                "status": "ACTIVE" if year == latest_year else "ARCHIVED",
                "created_by_id": group.treasurer_id,
                "archived_at": now if year != latest_year else None,
            }
            cycle, _ = FinancialCycle.objects.get_or_create(
                group_id=group.id,
                cycle_name=cycle_name,
                defaults=defaults,
            )
            cycle_map[(group.id, year)] = cycle.id

    for contribution in Contribution.objects.all().iterator():
        if not contribution.due_date:
            continue
        year = contribution.due_date.year
        cycle_id = cycle_map.get((contribution.group_id, year))
        if not cycle_id:
            continue

        expected = contribution.expected_amount
        if expected is None or expected <= Decimal("0.00"):
            expected = contribution.amount or Decimal("0.00")
        month_value = contribution.contribution_month or _month_start(contribution.due_date)

        Contribution.objects.filter(pk=contribution.pk).update(
            financial_cycle_id=cycle_id,
            contribution_month=month_value,
            expected_amount=expected,
        )

        actual_paid = contribution.amount if contribution.status in ("PAID", "LATE") else Decimal("0.00")
        payment_date = contribution.paid_date if actual_paid > Decimal("0.00") else None
        outstanding = expected - actual_paid
        if outstanding < Decimal("0.00"):
            outstanding = Decimal("0.00")

        if actual_paid <= Decimal("0.00"):
            status = "UNPAID"
        elif actual_paid < expected:
            status = "PARTIAL"
        else:
            status = "PAID"

        MonthlyContributionRecord.objects.update_or_create(
            user_id=contribution.user_id,
            group_id=contribution.group_id,
            financial_cycle_id=cycle_id,
            month=month_value,
            defaults={
                "expected_contribution_amount": expected,
                "actual_contribution_paid": actual_paid,
                "payment_date": payment_date,
                "outstanding_amount": outstanding,
                "status": status,
                "source_contribution_id": contribution.id,
            },
        )

    for investment in Investment.objects.all().iterator():
        if not investment.start_date:
            continue
        year = investment.start_date.year
        cycle_id = cycle_map.get((investment.group_id, year))
        if not cycle_id:
            continue
        Investment.objects.filter(pk=investment.pk).update(financial_cycle_id=cycle_id)

    for cycle in FinancialCycle.objects.all().iterator():
        total_contributions = Contribution.objects.filter(
            financial_cycle_id=cycle.id,
            status__in=["PAID", "LATE"],
            is_archived=False,
        ).aggregate(total=models.Sum("amount"))["total"] or Decimal("0.00")
        total_investments = Investment.objects.filter(
            financial_cycle_id=cycle.id,
            status__in=["APPROVED", "ACTIVE", "MATURED", "CLOSED"],
            is_archived=False,
        ).aggregate(total=models.Sum("amount_invested"))["total"] or Decimal("0.00")

        FinancialCycle.objects.filter(pk=cycle.pk).update(
            total_contributions=total_contributions,
            total_investments=total_investments,
        )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0002_group_is_penalty_enabled_group_min_saving_amount_and_more"),
        ("finance", "0010_investmentreturn"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialCycle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cycle_name", models.CharField(max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("CLOSED", "Closed"), ("ARCHIVED", "Archived")], default="ACTIVE", max_length=20)),
                ("total_contributions", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("total_investments", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("total_returns", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_financial_cycles", to=settings.AUTH_USER_MODEL)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="financial_cycles", to="groups.group")),
            ],
            options={
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CycleClosureReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_expected_contributions", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("total_collected_contributions", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("contribution_fulfillment_rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("member_payment_consistency_score", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("outstanding_totals", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("cycle", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="closure_report", to="finance.financialcycle")),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddField(
            model_name="contribution",
            name="contribution_month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="expected_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="contribution",
            name="financial_cycle",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contributions", to="finance.financialcycle"),
        ),
        migrations.AddField(
            model_name="contribution",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contribution",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contribution",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="MonthlyContributionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField(help_text="First day of the contribution month.")),
                ("expected_contribution_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("actual_contribution_paid", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("outstanding_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("status", models.CharField(choices=[("PAID", "Paid"), ("PARTIAL", "Partial"), ("UNPAID", "Unpaid")], default="UNPAID", max_length=20)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("financial_cycle", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="monthly_records", to="finance.financialcycle")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_contribution_records", to="groups.group")),
                ("source_contribution", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="monthly_records", to="finance.contribution")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_contribution_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-month", "user_id"],
            },
        ),
        migrations.AddField(
            model_name="investment",
            name="decision_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="investment",
            name="financial_cycle",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="investments", to="finance.financialcycle"),
        ),
        migrations.AddField(
            model_name="investment",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="investment",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="reviewed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_investments", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name="contribution",
            options={"ordering": ["due_date", "created_at"]},
        ),
        migrations.AddConstraint(
            model_name="financialcycle",
            constraint=models.UniqueConstraint(fields=("group",), condition=Q(status="ACTIVE"), name="unique_active_financial_cycle_per_group"),
        ),
        migrations.AddConstraint(
            model_name="financialcycle",
            constraint=models.UniqueConstraint(fields=("group", "cycle_name"), name="unique_financial_cycle_name_per_group"),
        ),
        migrations.AddConstraint(
            model_name="monthlycontributionrecord",
            constraint=models.UniqueConstraint(fields=("user", "group", "financial_cycle", "month"), name="unique_monthly_contribution_record"),
        ),
        migrations.RunPython(seed_cycles_and_monthly_records, migrations.RunPython.noop),
    ]
