# Generated by Django 5.2.10 on 2026-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('ACTIVATION', 'Activation'), ('DEACTIVATION', 'Deactivation'), ('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset'), ('ROLE_CHANGE', 'Role Change')], max_length=20),
        ),
    ]
