# Generated by Django 5.2.10 on 2026-02-24 14:33

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[accounts.validators.validate_profile_picture_size]),
        ),
    ]
