# Generated by Django 5.2.10 on 2026-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_auditlog_target_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('ACTIVATION', 'Activation'), ('DEACTIVATION', 'Deactivation'), ('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset'), ('ROLE_CHANGE', 'Role Change'), ('CONTRIBUTION_ADD', 'Contribution Add'), ('PENALTY_ISSUE', 'Penalty Issue')], max_length=20),
        ),
    ]
