# Generated by Django 5.2.10 on 2026-08-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('ACTIVATION', 'Activation'), ('DEACTIVATION', 'Deactivation'), ('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset'), ('ROLE_CHANGE', 'Role Change'), ('CONTRIBUTION_ADD', 'Contribution Add'), ('PENALTY_ISSUE', 'Penalty Issue'), ('MEMBERSHIP_CHANGE', 'Membership Change'), ('FINANCE_CHANGE', 'Finance Change'), ('FINANCE_ARCHIVE', 'Finance Archive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TREASURER', 'Treasurer'), ('FINANCIAL_SECRETARY', 'Financial Secretary'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
