from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ContributionViewSet,
    PenaltyViewSet,
    FinancialInsightsView,
    AutoSavingConfigViewSet,
    SavingsTargetViewSet,
    InvestmentViewSet,
    FinancialCycleViewSet,
    MonthlyContributionReportViewSet,
    CycleAnnualSummaryView,
    FinancialDataAuditView,
    AdminAddContributionView,
    AdminResetMemberFinanceView,
    AdminMemberListView,
    AdminGroupSummaryView,
    FinancialReportView,
    TriggerAutoSaveView,
    AutoSavingGenerationHistoryView,
    MemberAnalyticsView,
    GroupAnalyticsView,
    FinancialSecretaryReportView,
)

# Create a DRF router and register the ViewSets
router = DefaultRouter()
router.register(r"contributions", ContributionViewSet, basename="contribution")
router.register(r"penalties", PenaltyViewSet, basename="penalty")
router.register(r"auto-savings", AutoSavingConfigViewSet, basename="auto-saving")
router.register(r"targets", SavingsTargetViewSet, basename="savings-target")
router.register(r"investments", InvestmentViewSet, basename="investment")
router.register(r"financial-cycles", FinancialCycleViewSet, basename="financial-cycle")
router.register(
    r"monthly-contributions",
    MonthlyContributionReportViewSet,
    basename="monthly-contribution-report",
)

urlpatterns = [
    # Include all routes generated by the router
    path("", include(router.urls)),
    path("insights/", FinancialInsightsView.as_view(), name="financial-insights"),
    path("admin-add-contribution/", AdminAddContributionView.as_view(), name="admin-add-contribution"),
    path(
        "admin-reset-member-finance/",
        AdminResetMemberFinanceView.as_view(),
        name="admin-reset-member-finance",
    ),
    path(
        "admin-member-list/",
        AdminMemberListView.as_view(),
        name="admin-member-list",
    ),
    path(
        "admin-group-summary/",
        AdminGroupSummaryView.as_view(),
        name="admin-group-summary",
    ),
    path("reports/summary/", FinancialReportView.as_view(), name="financial-report-summary"),
    path("reports/financial/", FinancialSecretaryReportView.as_view(), name="financial-report-secretary"),
    path("reports/annual/", CycleAnnualSummaryView.as_view(), name="financial-report-annual"),
    path("trigger-auto-save/", TriggerAutoSaveView.as_view(), name="trigger-auto-save"),
    path("auto-save-history/", AutoSavingGenerationHistoryView.as_view(), name="auto-save-history"),
    path("analytics/member/", MemberAnalyticsView.as_view(), name="analytics-member"),
    path("analytics/group/", GroupAnalyticsView.as_view(), name="analytics-group"),
    path("data-audit/", FinancialDataAuditView.as_view(), name="financial-data-audit"),
]
