from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ContributionViewSet,
    PenaltyViewSet,
    FinancialInsightsView,
    AutoSavingConfigViewSet,
    SavingsTargetViewSet,
    InvestmentViewSet,
    AdminAddContributionView,
)

# Create a DRF router and register the ViewSets
router = DefaultRouter()
router.register(r"contributions", ContributionViewSet, basename="contribution")
router.register(r"penalties", PenaltyViewSet, basename="penalty")
router.register(r"auto-savings", AutoSavingConfigViewSet, basename="auto-saving")
router.register(r"targets", SavingsTargetViewSet, basename="savings-target")
router.register(r"investments", InvestmentViewSet, basename="investment")

urlpatterns = [
    # Include all routes generated by the router
    path("", include(router.urls)),
    path("insights/", FinancialInsightsView.as_view(), name="financial-insights"),
    path("admin-add-contribution/", AdminAddContributionView.as_view(), name="admin-add-contribution"),
]
