# Generated by Django 5.2.10 on 2026-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_penalty_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='min_saving_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='savings_interval',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_auto_penalty_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
