# Generated by Codex on 2026-03-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_is_penalty_enabled_group_min_saving_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                related_query_name="memberships",
                to="groups.group",
            ),
        ),
    ]
