# Generated by Django 5.2.10 on 2026-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_membership_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('TREASURER', 'Treasurer'), ('FINANCIAL_SECRETARY', 'Financial Secretary'), ('MEMBER', 'Member')], max_length=20),
        ),
    ]
