# Generated by Django 5.2.10 on 2026-08-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_category_notificationpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_APPROVED", "Account Approved"),
                    ("ACCOUNT_REJECTED", "Account Rejected"),
                    ("ACCOUNT_ACTIVATION", "Account Activation"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("CONTRIBUTION_RECEIVED", "Contribution Received"),
                    ("CONTRIBUTION_REMINDER", "Contribution Reminder"),
                    ("CONTRIBUTION_PROPOSAL", "Contribution Proposal"),
                    ("INVESTMENT_CREATED", "Investment Created"),
                    ("INVESTMENT_UPDATE", "Investment Update"),
                    ("GROUP_ANNOUNCEMENT", "Group Announcement"),
                    ("MEMBERSHIP_ADDED", "Membership Added"),
                    ("PENALTY_ISSUED", "Penalty Issued"),
                    ("SECURITY_ALERT", "Security Alert"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_token", models.TextField(unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("WEB", "Web"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
    ]
