# Generated by Django 5.2.10 on 2026-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_delivery_preferences_and_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ACCOUNT_APPROVED', 'Account Approved'), ('ACCOUNT_REJECTED', 'Account Rejected'), ('ACCOUNT_ACTIVATION', 'Account Activation'), ('PASSWORD_RESET', 'Password Reset'), ('CONTRIBUTION_RECEIVED', 'Contribution Received'), ('CONTRIBUTION_APPROVED', 'Contribution Approved'), ('CONTRIBUTION_REMINDER', 'Contribution Reminder'), ('CONTRIBUTION_PROPOSAL', 'Contribution Proposal'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_REJECTED', 'Loan Rejected'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('LOAN_REPAYMENT_RECEIVED', 'Loan Repayment Received'), ('LOAN_REPAYMENT_VERIFIED', 'Loan Repayment Verified'), ('LOAN_OVERDUE', 'Loan Overdue'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_UPDATE', 'Investment Update'), ('GROUP_ANNOUNCEMENT', 'Group Announcement'), ('MEMBERSHIP_ADDED', 'Membership Added'), ('PENALTY_ISSUED', 'Penalty Issued'), ('SECURITY_ALERT', 'Security Alert'), ('GENERAL', 'General')], default='GENERAL', max_length=40),
        ),
    ]
